[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
network = { path = "../../lib/network" }
base = { path = "../../lib/base" }
game-server = { path = "../../game/game-server", default-features = false }
game-base = { path = "../../game/game-base" }
game-config = { path = "../../game/game-config" }

serde_json = "1.0.134"
env_logger = "0.11.6"

[features]
legacy = ["game-server/legacy"]

default = ["legacy"]
