[package]
name = "assets-server"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../../lib/base" }
image-utils = { path = "../../lib/image-utils" }

assets-base = { path = "../../game/assets-base" }

tokio = { version = "1.44.2", features = ["rt-multi-thread", "sync", "fs", "net", "time", "macros"] }
anyhow = { version = "1.0.98", features = ["backtrace"] }
axum = { version = "0.8.3" }

tower-http = { version = "0.6.2", features = ["fs", "trace"] }
tower-service = { version = "0.3.3" }
serde_json = "1.0.140"
clap = { version = "4.5.36", features = ["derive"] }
urlencoding = "2.1.3"
parking_lot = "0.12.3"
log = "0.4.27"
env_logger = "0.11.8"
dotenvy = "0.15.7"
