blank_issues_enabled: true
contact_links:
  - name: Questions (discord)
    url: https://ddnet.org/discord
    about: Please ask questions in our official discord.
  - name: Feature requests, refactors & concepts
    url: https://github.com/ddnet/ddnet-rs-rfc
    about: Please use our rfc repository for feature requests, concepts or bigger refactors. You can also discuss such things in our chat rooms (discord etc.)
  - name: Questions (Matrix & IRC)
    url: https://matrix.to/#/#ddnet:ddnet.org
    about: 'Please ask questions in our official Matrix space. Or on irc #ddnet. It''s bridged to discord.'


