blank_issues_enabled: true
contact_links:
  - name: Questions (discord)
    url: https://ddnet.org/discord
    about: Please ask questions in our official discord.
  - name: Feature requests, refactors & concepts
    url: https://github.com/ddnet/ddnet-rs-rfcs
    about: Please use our rfc repository for feature requests, concepts or bigger refactors. You can also discuss such things in our chat rooms (discord etc.)
  - name: Questions (Matrix)
    url: https://matrix.to/#/#ddnet:ddnet.org
    about: Please ask questions in our official Matrix space. It's bridged to discord
  - name: Questions (IRC) #ddnet
    about: We also have a IRC channel bridged to discord.


