[package]
name = "community-register-server"
version = "0.1.0"
edition = "2021"

[dependencies]
community = { path = "../../game/community" }

tokio = { version = "1.45.0", features = ["rt-multi-thread", "sync", "fs", "net", "time", "macros"] }
anyhow = { version = "1.0.98", features = ["backtrace"] }
axum = "0.8.4"
clap = { version = "4.5.37", features = ["derive"] }

tower-http = { version = "0.6.2", features = ["fs", "trace"] }
