[package]
name = "api-auto-mapper"
version = "0.1.0"
edition = "2021"

[dependencies]
editor-interface = { path = "../editor-interface" }

api = { path = "../../lib/api" }
api-wasm-macros = { path = "../../lib/api-wasm-macros" }

once_cell = "1.20.2"
