[package]
name = "editor-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
map = { path = "../map" }

serde = { version = "1.0.219", features = ["derive"] }
anyhow = { version = "1.0.97", features = ["backtrace"] }
