[package]
name = "game-base"
version = "0.1.0"
edition = "2021"

[dependencies]
math = { path = "../../lib/math" }
base = { path = "../../lib/base" }
image-utils = { path = "../../lib/image-utils" }
graphics-types = { path = "../../lib/graphics-types" }
config = { path = "../../lib/config" }
command-parser = { path = "../../lib/command-parser" }
pool = { path = "../../lib/pool" }
hiarc = { path = "../../lib/hiarc", features = ["enable_time"] }

map = { path = "../map" }
game-interface = { path = "../game-interface" }
game-config = { path = "../game-config" }

rayon = "1.10.0"
num-derive = "0.4.2"
num-traits = "0.2.19"
flate2 = "1.1.1"
anyhow = { version = "1.0.98", features = ["backtrace"] }
hashlink = { git = "https://github.com/Jupeyy/hashlink/", branch = "ddnet", features = ["serde", "serde_impl"] }
serde = { version = "1.0.219", features = ["derive"] }
indexmap = "2.9.0"
time = { version = "0.3.41", features = ["serde"] }
serde_with = "3.12.0"
thiserror = "2.0.12"
itertools = "0.14.0"

[package.metadata.cargo-machete]
ignored = ["num-traits"]

[dev-dependencies]
rustc-hash = "2.1.1"
