name: Publish Release (Test)

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

permissions:
  contents: write
  actions: read

jobs:
  release:
    name: Publish Test Tagged Release
    # only run if Build succeeded, repo is not a fork, and the ref is a test tag
    if: ${{ github.event.workflow_run.conclusion == 'success' &&
            startsWith(github.event.workflow_run.head_branch, 'test-v') &&
            !github.event.workflow_run.repository.fork }}
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ github.event.workflow_run.id }}
        pattern: ddnet-rs-*
        merge-multiple: false
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Re-zip each artifact folder with original name
      run: |
        set -euo pipefail
        mkdir -p release-artifacts
        shopt -s nullglob
        for d in ddnet-rs-*; do
          if [ -d "$d" ]; then
            echo "Zipping contents of $d -> release-artifacts/$d.zip"
            (
              cd "$d"
              zip -qr "../release-artifacts/$d.zip" *
            )
          fi
        done

    - name: Generate BLAKE3 checksums
      run: |
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y b3sum
        cd release-artifacts
        echo "${{ github.event.workflow_run.head_sha }}" > blake3_checksum.txt
        for f in *.zip; do
          hash=$(b3sum "$f" | awk '{print $1}')
          echo "$f $hash" >> blake3_checksum.txt
        done

    - name: Create GitHub Test Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.workflow_run.head_branch }}
        target_commitish: ${{ github.event.workflow_run.head_sha }}
        name: Test Release ${{ github.event.workflow_run.head_branch }}
        body: |
          Automated test release from fork.
          Commit: ${{ github.event.workflow_run.head_sha }}
        draft: false
        prerelease: true
        make_latest: false
        files: |
          release-artifacts/*.zip
          release-artifacts/blake3_checksum.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
