name: Publish Release (Test)

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

permissions:
  contents: write
  actions: read

jobs:
  release:
    name: Publish Test Tagged Release
    # Build erfolgreich + Event ist push + Tag beginnt mit test-v
    if: ${{ github.event.workflow_run.conclusion == 'success'
            && github.event.workflow_run.event == 'push'
            && startsWith((github.event.workflow_run.head_branch || ''), 'test-v') }}
    runs-on: ubuntu-latest
    steps:
    - name: Debug workflow_run context (optional)
      run: |
        echo "event            = ${{ github.event.workflow_run.event }}"
        echo "head_branch      = ${{ github.event.workflow_run.head_branch }}"
        echo "head_sha         = ${{ github.event.workflow_run.head_sha }}"
        echo "repo.fork        = ${{ github.event.workflow_run.repository.fork }}"

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ github.event.workflow_run.id }}
        pattern: ddnet-rs-*
        merge-multiple: false
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Re-zip each artifact folder with original name
      run: |
        set -euo pipefail
        mkdir -p release-artifacts
        shopt -s nullglob
        for d in ddnet-rs-*; do
          if [ -d "$d" ]; then
            ( cd "$d" && zip -qr "../release-artifacts/$d.zip" * )
          fi
        done

    - name: Generate BLAKE3 checksums
      run: |
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y b3sum
        cd release-artifacts
        echo "${{ github.event.workflow_run.head_sha }}" > blake3_checksum.txt
        for f in *.zip; do
          hash=$(b3sum "$f" | awk '{print $1}')
          echo "$f $hash" >> blake3_checksum.txt
        done

    - name: Create GitHub Test Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.workflow_run.head_branch }}                 # <- Tag-Name
        target_commitish: ${{ github.event.workflow_run.head_sha }}
        name: Test Release ${{ github.event.workflow_run.head_branch }}
        body: |
          Automated test release from fork.
          Commit: ${{ github.event.workflow_run.head_sha }}
        draft: false
        prerelease: true
        make_latest: false
        files: |
          release-artifacts/*.zip
          release-artifacts/blake3_checksum.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
